### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by GhalemB** [sanyi/ipsetpy#5]

**Comment by GhalemB** [comment]
Hi,
Is there a version or recommandation to use ipsetpy with Python2.7 ?
I managed to make it working through disabling some exceptions (lines 25 and 42 to 46).
Thanking you in advance for answers.
G.

**Comment by sanyi** [comment]
Hi, I did not intended to support Python 2.x within this project. Since you figured out how to make this code 2.7 compatible, I would suggest to fork the code and create a library for 2.x.
